name: Build & Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to AWS S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Installs Orion & builds the blog
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/adriantombu/orion
          orion build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy files to AWS S3
        run: |
          aws s3 sync ./docs s3://${{ secrets.AWS_BUCKET_ID }} --exclude '.git/*' --exclude '.github/*' --exclude '.DS_Store' --delete
